[package]
name = "yolo-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = "0.92.2" # you may adjust the version according to system library
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
